### ISSUE TITLE
How to estimate the assembly graph  is an organelle-sufficient graph?

### ISSUE THREAD

**Issue by zgszm** [Kinggerm/GetOrganelle#122]
chloroplast
![cp](https://user-images.githubusercontent.com/96463605/148029351-bac1e18b-514f-482f-81ac-3364cfee259c.png)
mitochondrion
![graph](https://user-images.githubusercontent.com/96463605/148029692-89d2ea43-2340-4065-8e18-4279da2218a6.png)

**Comment by Kinggerm** [comment]
Generally, if the graph component 
1) contains all the possible target genes (sometimes there may be gene losses), 
2) contains even coverage (repeats can be multiple times) 
3) has a circular path that can traverse the graph component (with contig multiplicities proportional to the coverage)

In your case, neither the pt and mt are organelle-sufficient.
1. The pt graph do not have a circular path because `18891400` and `18890422` are not connected. It is near complete though. You can do some parameter optimization to improve it.
2. The mt graph are highly fragmented and contains one pt contig (`12723318`) kept by mistake.

**Comment by zgszm** [comment]
The two graphs is (embplant_pt.K105.complete.graph1.selected_graph).gfa, which is different with (extended_K105.assembly_graph).fastg

I compare with the test "Arabidopsis_simulated", the ().gfa is exactly alike with ().fastq

The cp ().fastq(my data)
![1](https://user-images.githubusercontent.com/96463605/148192957-e20f169d-79c9-4685-9a68-b5626338f6b4.png)

I should inspect the ().fastq?

**Comment by Kinggerm** [comment]
> The two graphs is (embplant_pt.K105.complete.graph1.selected_graph).gfa, which is different with (extended_K105.assembly_graph).fastg
> 
> I compare with the test "Arabidopsis_simulated", the ().gfa is exactly alike with ().fastq
> 
> The cp ().fastq(my data) ![1](https://user-images.githubusercontent.com/96463605/148192957-e20f169d-79c9-4685-9a68-b5626338f6b4.png)
> 
> Is there any difference between ().gfa and ().fastq? I should inspect the ().fastq?

I cannot understand you here. Please correct the obvious grammar mistakes and reorganize your question to make it clearer. Besides, make sure it is related to the issue.

**Comment by zgszm** [comment]
My question: Is there any difference between ().gfa and ().fastq?

**Comment by zgszm** [comment]
The ().fastq graph
![1](https://user-images.githubusercontent.com/96463605/148319190-5632daf3-a9ac-405c-b554-a9376bfbd2bd.png)
Is this result a complete chloroplast genome?
Are the following fragments a part of cp genome?
Thank you for your answers

**Comment by Kinggerm** [comment]
> My question: Is there any difference between ().gfa and ().fastq?

This is totally another issue. To avoid making miscellaneous issue, I opened another issue for this question. Please find the answer at #124 

You may leave further comments or questions. But do not branch out inside one issue.  If your question concerning this issue was answered, please close this issue.
