### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by jiangyinz** [Kinggerm/GetOrganelle#123]
Hi,
I have updated GetOrganelle to the latest version 1.7.5.2, but this problem cannot be fixed.
Does someone have ideas of what I need to do? Thanks in advance!! #119
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/7807644/get_org.log.txt)

**Comment by Kinggerm** [comment]
The same Python `ValueError: max() arg is an empty sequence` does not mean it relate to 119. And it is not related.

This error was triggered because no valid read passed the criterion that it must be larger than the word size. You input an arbitrary word size (-w 105) when your read length is 90. Please always read the [homepage guidelines](https://github.com/Kinggerm/GetOrganelle#recipes) and use the suggested command unless you know what the changes mean, before running any bio-softwares.

Another important `error`  is you did not have sympy/scipy installed. Please always follow the official guidelines.
