### ISSUE TITLE
Spontaneous error with python "index out of range"

### ISSUE THREAD

**Issue by sivico26** [Kinggerm/GetOrganelle#13]
Hi, @Kinggerm,

I am trying to use GetOrganelle to assemble both the chloroplast and the mitochondrion of my plant. In the process I have been facing an "index out of range error" from python (that goes to stderr):

```
Traceback (most recent call last):
  File "/home/svillanu/Programs/GetOrganelle/get_organelle_from_reads.py", line 3502, in <module>
    main()
  File "/home/svillanu/Programs/GetOrganelle/get_organelle_from_reads.py", line 3142, in main
    options, log_handler, previous_attributes = get_options(description=title, version=get_versions())
  File "/home/svillanu/Programs/GetOrganelle/get_organelle_from_reads.py", line 570, in get_options
    dep_versions_info.append("Blast " + this_lines[1].strip().split()[2].replace(",", "").strip())
IndexError: list index out of range
```

In the beginning, I managed to get chloroplast running, and this error just appeared when I tried to assemble the mitochondrion. But as that process failed, and I resubmitted I'm getting the same error with the chloroplast as well (without changing anything). The following is one example of this problem. The log is not very informative though:

Log: 
```
GetOrganelle v1.6.1a

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56)  [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
Python libs: numpy 1.16.4; sympy 1.4; scipy 1.3.0

GetOrganelle v1.6.1a

get_organelle_from_reads.py assembles organelle genomes from genome skimming data.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56)  [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
Python libs: numpy 1.16.4; sympy 1.4; scipy 1.3.0
```

Here is the command line that produces it:

```
get_organelle_from_reads.py -1 $pe1 -2 $pe2 -o $output -F embplant_pt -t $threads -k 21,45,65,85,105 --max-reads=10E7 --which-blast $blast --which-bandage $bandage
```
Where:
```
threads=$SLURM_CPUS_PER_TASK   ## 16 
folder=$(pwd)
pe1="$folder/reads/WGS_pe1.fastq"
pe2="$folder/reads/WGS_pe2.fastq"
output="$folder/output"
blast="/home/svillanu/Programs/GetOrganelle/GetOrganelleDep/linux/ncbi-blast"
bandage="/home/svillanu/.conda/envs/Spades/bin"
```

Something that I find curious, is that at the beginning, as aforementioned, the chloroplast process was running ok, but the mitochondrion presented this error; Even though it is exactly the same configuration (same data and parameters), it only changes the `-F` option to `embplant_mt`.

Do you have any idea of what could be happening here?
Thanks in advance!

**Comment by Kinggerm** [comment]
This issue happened after v1.6.0 when "blastn" is not executable. You can prove this by executing `/home/svillanu/Programs/GetOrganelle/GetOrganelleDep/linux/ncbi-blast/blastn -version` directly, you would probably get `/lib64/libc.so.6: version `GLIBC_2.14' not found`. This happened because the attached ncbi-blast version may be too high for your system. I guess you got this issue because updated GetOrganelle after you finished the previous successful chloroplast running.

One temperate solution for this is ①if you installed GetOrganelle in the `in situ` way, delete the folder `/home/svillanu/Programs/GetOrganelle/GetOrganelleDep/linux/ncbi-blast/` (GetOrganelle would then automatically use the `blastn` in the $PATH); ②if you installed GetOrganelle in the `setup.py` way, delete the folder `/home/svillanu/Programs/GetOrganelle/GetOrganelleDep/linux/ncbi-blast/` then use the `pip` to reinstall. I guess you used the `in situ` way.

I would fix or at least give better instruction for this issue in the coming v1.6.2 (under testing and almost done). Good luck with your study!

**Comment by sivico26** [comment]
You were absolutely right, GLIBC_2.14 was the problem. I have been familiar with this kind of issues with other programs. 

I deleted the folder as you said, and installed blast from bioconda in the same environment where I put the python packages. Seems like it solved the problem as both are running right now. 

Just as a curiosity, have you considered making a bioconda package for GetOrganelle? Would make it way easier to install and I think would help to alleviate this kind of dependencies issues.

Thanks for the fast reply and the solution!

**Comment by Kinggerm** [comment]
Thanks for the suggestion. I would add it to the plan, although it would not be very soon.
