### ISSUE TITLE
Disentangling failed: 'Incomplete/Complicated graph'

### ISSUE THREAD

**Issue by erike07** [Kinggerm/GetOrganelle#134]
Hi. I'm having some problems when I try to assemble a fish mitogenome and meet a problem (Disentangling failed: 'Incomplete/Complicated graph').
I'm using some FASTA archives with -s of fishes at a 'near' family.
I've tried to reduce -w to 65 as the tutorial said but the result is the same.
Here is my log file and result files:
[rineloricaria-lanceolata.zip](https://github.com/Kinggerm/GetOrganelle/files/8008346/rineloricaria-lanceolata.zip)
Sorry for bad english, it isn't my native language.

Can you help me?

**Comment by Kinggerm** [comment]
Disentangling failed is not an error. This is a common when the target genome is complicated, e.g. abundant repeats. Next time please open a discussion in the Q&A session https://github.com/Kinggerm/GetOrganelle/discussions/categories/q-a, rather than opening an issue here. Thanks!

As for your question, according to the graph of `extended_K115.assembly_graph.fastg.extend-animal_mt.fastg`, the current result (nearly complete) is close to the best we can get from current sequencing reads, because there are too many short repeats in one part (maybe the D-loop) of the genome.

You may go ahead annotating the current scaffold, which should have almost all genes you need.
