### ISSUE TITLE
How to solve the problem of decompression in chloroplast genome assembly

### ISSUE THREAD

**Issue by zhaoying888** [Kinggerm/GetOrganelle#160]
For the same sample, ITS can assemble the result normally, but CP has an error of decompression failure. I can decompress the original command normally by using the decompression command
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/8460626/get_org.log.txt)

**Comment by Kinggerm** [comment]
You had exactly the same issue many times. Please always check the data integrity before running. `md5` checking must be done during receiving and transferring the data).

The ITS can be assembled but CP cannot because CP requires more reads to be unzipped from the same file. The ITS assembly did not reach the damaged part of the data.
