### ISSUE TITLE
Very detailed graph and chloroplast similar to published relatives in statistics but does not align correctly

### ISSUE THREAD

**Issue by Mondlii** [Kinggerm/GetOrganelle#188]
Hi, Thank you for such a convenient and helpful tool. I have been trying to get a chloroplast genome assembled since getting enough genome assembly data to play around with. The first issue I come across is that I get a disentanglement error when I use illumina reads that have had their contaminants removed using Kraken, however, that issue is not there when using the raw data sets. I have over 100x coverage of a 680Mb genome, so that's over 70GB of reads that I just feed to the tool. The issue that concerns me is that I tried to align all 4 produced fasta files against multiple chloroplast genomes from close relatives, and none of them align properly. The other genomes align properly with no signs of inversions or potential mis-assemblies. The statistics (Total size, LSC, SSC, IR are very comparable and seem to be accurate but the issue is in aligning downstream. I tried looking at the graph file as suggested in the log, but it looks nothing like any of the graphs I've  been able to find on the issues here. Please see below the graph and log files from the run. 

Thank you

![graph](https://user-images.githubusercontent.com/81998129/187273686-071a4890-6279-42a7-836a-91ad5200c7a6.png)
[get_org.log.txt](http
[extended_K115.assembly_graph.fastg.extend-embplant_pt-embplant_mt.fastg.txt](https://github.com/Kinggerm/GetOrganelle/files/9447101/extended_K115.assembly_graph.fastg.extend-embplant_pt-embplant_mt.fastg.txt)
s://github.com/Kinggerm/GetOrganelle/files/9447099/get_org.log.txt)

**Comment by JianjunJin** [comment]
The log file was not properly submitted. 

But according to the provided *fastg file, your run should be finished normally and successfully. Yes, we recommend using raw data with only adaptors removed (see [instruction at home page](https://github.com/Kinggerm/GetOrganelle#instruction)).

You should have obtained a gfa file with simplified graph as follows
![graph](https://user-images.githubusercontent.com/39948588/187277459-47750b44-15c3-416d-8f9d-06d9da02e395.svg)
In this simplified graph, you can see a pair of 466-bp short inverted repeats located inside LSC, which is the may reason that you get doubled number of sequences. This pair of short inverted repeats may not be solvable with Illumina data. You may need to use PCR to verify the order if your study requires a sturdy genome structure information. Actually, in many studies, both candidates may coexist, meaning genomic isomers coexist.

As it comes to your question on alignable, please check the following two FAQs first to exclude arbitrary order impact:
[1. What are the differences of complete*.1.path_sequence.fasta and complete*.2.path_sequence.fasta output files?](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#what-are-the-differences-of-complete1path_sequencefasta-and-complete2path_sequencefasta-output-files)
[2. How does GetOrganelle choose the start point and strand for a circular genome?](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#how-does-getorganelle-choose-the-start-point-and-strand-for-a-circular-genome)
After confirming that the bad colinearity is true and not because of ignoring above two issues, you may confirm it as real plastome rearrangement, which is actually common in a number of lineages.

**Comment by Mondlii** [comment]
Thank you for your response and assistance with this. I have looked at the suggested FAQs and even after trying to use the generated graph below (get_organelle_from_assembly.py)  the rearrangements persist. The chloroplast assembly is a supplementary addition to the study, and this possible rearrangement could actually add some more insight and information for the species and genus. I have also used mauve to align the four fasta files against the references and it seems all the major regions are present, but just in different orientation. Thank you for the help and very convenient tool.  
![graph](https://user-images.githubusercontent.com/81998129/187440500-2827b299-ca4f-4605-a168-0ea7f575013e.png)
