### ISSUE TITLE
Save unused reads

### ISSUE THREAD

**Issue by ernesfranco** [Kinggerm/GetOrganelle#189]
Hi!

Thank you for developing GetOrganelle! It is a fantastic tool!

Not an issue, just a question: I would like to ask if it is possible to save the unused/unmapped reads into a directory?

Thank you!

**Comment by Kinggerm** [comment]
Sorry for the slow reply. It may be complicated because GetOrganelle is doing post-assembly graph processing including graph component pruning. The final complete organelle genome may be the direct result of a small portion of the `extended reads`.

I would recommend finishing the GetOrganelle assembly to get a complete organelle result, then mapping the raw reads to the assembly using Bowtie2 or BWA, which has options for saving unmapped reads.

**Comment by ernesfranco** [comment]
Okay, thank you for the suggestion!
