### ISSUE TITLE
Mitochondrial Genome Assembly failed, please help

### ISSUE THREAD

**Issue by Silverfoxcome** [Kinggerm/GetOrganelle#20]
Hi!
I was trying to assemble the mitochondria of purple maize. 

My data is heavy (254,4 GB), with a total of  695510624 paired-end reads in both fastq files.

I run GetOrganelle with the following options:

> get_organelle_from_reads.py -1 trimmed_1P.fq -2 trimmed_2P.fq --max-reads=7.5E7 -s zm_mt_ref.fasta --target-genome-size 570000 -o getorg_1 -R 50 -k 21,45,65,85,105 -P 1000000 -F embplant_mt -t 8 --verbose --prefix=zm.mt  

Because my dataset was large, I put the option --max-reads=7.5E7. I was afraid of running the program with the whole dataset and make things wrong. 

But the mitochondria assembly failed. 
The Bandage plot looks like the following:
![graph_v3](https://user-images.githubusercontent.com/11965123/62300935-2d878c80-b467-11e9-85c0-4ecafc5b64ed.png)
(this is the one called zm.mtfiltered_K105.assembly_graph.fastg.extend-embplant_mt-embplant_pt.fastg in the ouput folder)

![zm mtembplant_mt K105 contigs graph1 selected_graph](https://user-images.githubusercontent.com/11965123/62301056-6293df00-b467-11e9-9b9a-7cdff4075892.png)

Here is my log file: 
[zm.mtget_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/3457084/zm.mtget_org.log.txt)

I read the advice you gave to harish0201 (https://github.com/Kinggerm/GetOrganelle/issues/6) and thought that perhaps I could make something similar?

Please, let me know if there are any parameters I could change to obtain better results. And if perhaps I should use more of my read dataset? 

Thanks a lot in advance :)

**Comment by Kinggerm** [comment]
I think your situation is different from #6 . You have actually get the **mitogenome-sufficient graph** according to your Bandage plot - no break point. 

Answers to your questions:
No parameters/dataset change needed.

Your challenges are mainly as follows:
1. Plastid contigs (ca. 160×) remains. Part of plastome might probably transferred into mitogenome in your sample. Some pt contigs, such as left bottom ones, seems not removable. If you manually remove it, the 6641-bp contig is a terminal contig and the whole graph is broken here. So you should probably include the plastid part, otherwise your mitogenome would be incomplete. This dilemma may be true if plastome does transfer into mitogenome. But another reason could be the assembly mistake. You can check result from other kmers to confirm this.
2. Two many repeats. Generally unsolvable with current type of dataset. 3rd generation sequencing might help.

In all, you could extract genes from current assembly result, rather than genome architecture.

**Comment by Silverfoxcome** [comment]
Here the graph, with the csv information (a lot more informative now! :O!! thank you!) 
![graph_v4](https://user-images.githubusercontent.com/11965123/62322826-79e9c100-b495-11e9-9e75-599bc93232c4.png)

A few doubs please. I'm very new to this field of bioinformatics and genome assembly.
Please, could you explain what do you mean by "terminal contig and the whole graph is broken here"?

> You can check result from other kmers to confirm this.

If I check the fastg of the other kmers, and see a contig equal to that terminal 6641-bp contig, would this verify that plastome sequences did transfer to the mitogenome, right?

Thank you so much for your help :)

**Comment by Kinggerm** [comment]
When I referred `terminal contig`, I mean a contig without connections at both ends of it, such as the left blue contig of [this graph](https://user-images.githubusercontent.com/9093815/53932975-56774180-40c2-11e9-90f0-aa222b54f383.png).

At this moment, I have to say no to the second question. I mean you have to check whether other kmers offer graphs that cp contigs could be easily removed without creating terminal contigs for the mitogenome assembly graph.
