### ISSUE TITLE
Batch works

### ISSUE THREAD

**Issue by NowickiLab** [Kinggerm/GetOrganelle#244]
Hello, Jianjun,

Have you ever considered incorporating a batch capability? Re: [novowrap -list](https://github.com/wpwupingwp/novowrap)

Thanks for any heads-up!
-Marcin

**Comment by JianjunJin** [comment]
Running GetOrganelle in a batch can be carried out by a for-loop in SHELL (recommended) or a batch file, e.g.

```
for i in `sample.list`; do get_organelle_from_assembly.py -1 ${i}_1.fq.gz -2 ${i}_2.fq.gz -F embplant_pt -o ${i}-pt >> ; done
```
Besides, in the [Utilities](https://github.com/Kinggerm/GetOrganelle/tree/master/Utilities), there is a script called [make_batch_for_get_organelle.py](https://github.com/Kinggerm/GetOrganelle/blob/master/Utilities/make_batch_for_get_organelle.py) can do a similar thing. I personally used the for-loop more often. Let me know if you have different thoughts.

Nevertheless, instead of using [any genera rules](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#how-does-getorganelle-choose-the-start-point-and-strand-for-a-circular-genome) as GetOrganelle and FastPlast do, ordering the plastome structure according to the reference as novowrap does, is appealing to people who want to have quick batch results for downstream analysis. I planned to incorporate something similar long ago. The difference would be a more general and robust solution for picking the ref-like structure from the de novo results. It has been put aside for a long time, though. But I'm sure it will be included in the next big release of 1.8.0.
