### ISSUE TITLE
Repeat of spades issues like  #152 and #83 with update to  getorganelle v1.7.7.0

### ISSUE THREAD

**Issue by bmillerlab** [Kinggerm/GetOrganelle#250]
Hello, 
I was running getorganelle on a macos with no problems (a great pipeline and builds really nice invertebrate mitochondrion for me - so THANKS!).  Then I realized there was an update (I had v1.7.5.3 installed through conda ).  After I ran the conda update I got an errors with spades.  Part of the error message is - ERROR: Error with running SPAdes: == Error ==  system call for: ...finished abnormally, err code: -6.  After some digging I saw this problem reared it's ugly head in the past and you fixed it when you released version 1.7.0 (I think that was why you made that release).  Anyway, the problems started with conda not actually installing updated versions of spades for macos and it is occurring again (I don't know if this is a problem on linux - there is a newer version available on bioconda for linux, but it does not work with macos).  I did try a variety of other install options including getting the tar.gz file from github but that spades file does not actually download correctly (despite using the specific instructions given to use curl http://cab.spbu.ru/files/release3.15.5/SPAdes-3.15.5-Darwin.tar.gz -o SPAdes-3.15.5-Darwin.tar.gz.

In the end I rolled my conda environment back to getorganelle  v1.7.5.3( pyh5e36f6f_0    bioconda) and it all works again. 

I realize this is a spades problem overall, but I'm putting this here in case someone else has a problem and also in case you decide you want to eventually offer another version of getorganelle that avoids this issue again.

Thanks for the great software pipeline.

**Comment by JianjunJin** [comment]
Thanks for the feedback. This is a painful one.

If you check the [release note](https://github.com/Kinggerm/GetOrganelle/releases/tag/1.7.7.0), GetOrganelle 1.7.7.0 actually has nothing to do with improving compatibility or fixing the error with SPAdes. Even though I packed an updated version of SPAdes to GetOrganelleDep and named it [1.7.0](https://github.com/Kinggerm/GetOrganelleDep/releases/tag/v1.7.0), it is just an option for people who use the setup.py to install the dependencies. There is no version bond between GetOrganelle and GetOrganelleDep (or SPAdes). We used to have a version limit in the conda system, but after [1.7.5.0](https://github.com/bioconda/bioconda-recipes/commit/827341cbe920b105b813b1604ca1d9c53d7fe1b7), which removed the upper version constraint of SPAdes, both upgrading or downgrading the versions of GetOrganelle should NOT influence the performance of SPAdes in theory. 

However, SPAdes is known to be not compliant with conda partially because the developers do not want to, and it is environmentally sensitive. While there are issues like #152 and #83 , not all users had them. We used to test the same SPAdes version in similar Linux systems and found even subtle differences can break it. While the developer claimed and most users reported that SPAdes could not run it in WSL, I got feedback from a few users that it works for them. It could be the architecture. We don't know if there is a list of which versions and what environments are compatible. 

When you upgrade or downgrade GetOrganelle using conda, in your case, the conda may change the other environment that destroys SPAdes. 

**The current solution for most SPAdes-issue users is installing SPAdes from the source, according to the SPAdes developer.** Users who installed GetOrganelle using conda should additionally uninstall the conda-installed spades or use `--which-spades` to guide GetOrganelle to the correct version.

I will 1) add more illustrations and 2) add an alternative assembler engine (probably Velvet) for users to choose from.

**Comment by Kinggerm** [comment]
I've just updated the GetOrganelle.wiki with SPAdes errors illustrated at [FAQ](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#spades-errors) and [Installation](https://github.com/Kinggerm/GetOrganelle/wiki/Installation).

**Comment by bmillerlab** [comment]
Hi Jianjun Jin,
Thank you for the detailed answer and explanation.  I just looked at the FAQ and Installation changes and if I run into more errors I will try the options listed.  Since everything is working right now, I think I am going to just stick with v1.7.5.3 so I can get finished with this part of my project!  I like the idea of possibly having another assembler like Velvet as an option someday.

Best,
