### ISSUE TITLE
Mitochondrial segment has been assmbled on the Chloroplast loop

### ISSUE THREAD

**Issue by Jiny000** [Kinggerm/GetOrganelle#26]
Hi,@Kinggerm!
I used Getorganelle to assemble Chloroplast.First time,I used total 1G data to assemble,which means about 500M per end with below code.
```sh
head -n 4444444 xx_L1_1.rd.fq >1.rd.fq
head -n 4444444 xx_L1_2.rd.fq >2.rd.fq
… #There are three lanes totally I used.
get_organelle_from_reads.py -1 1.rd.fq -2 2.rd.fq -o plastome_output -R 15 -k 21,45,65,85,105 -F embplant_pt -t 16"
```
![AY17_0](https://user-images.githubusercontent.com/56862503/70983145-2ea61700-20f3-11ea-80b1-57251236eeca.png)

The result is perfect.

Then I noticed that you advice to use 1G per end to assemble chloroplast.So I extracted more data.However,in this time,the extracting code is:
```sh
head -n 8888888 xx_L1_1.rd.fq >1.rd.fq
head -n 8888888 xx_L1_2.rd.fq >2.rd.fq
```
With the same codes in other steps,I got the result with a special  low-depth node in chloroplast loop.I blasted the node in NCBI,and found it is a segment of mitochondria.
![AY17x](https://user-images.githubusercontent.com/56862503/70983034-061e1d00-20f3-11ea-9d42-c3596c3b77af.png)
Then I thought it may be the result of 'head',so I used seqtk to extract.
```
seqtk sample -s11 xx_L1_1.rd.fq 2222222 >xx.1.1G.rd.fq
seqtk sample -s11 xx_L1_2.rd.fq 2222222 >xx.2.1G.rd.fq
```
The result became like this:
![AY17_SEQTK](https://user-images.githubusercontent.com/56862503/70983631-04a12480-20f4-11ea-86f7-b21ea5a088a8.png)
I had blasted two low-depth node ,they are just mitochondiral segments.

In one words,I used less data assemble successfully,but failed with more data.So is it normal to get a chloroplast with mitochondria segments?How can I get a pure chloroplast loop?Or it is ok to remove the node in bandage?

Thank you!

Best wishes

**Comment by Kinggerm** [comment]
Hi @Jiny000 

All those three results are perfect. You can take a look at the `get_org.log.txt` file. It must have told you successful and complete.
It's very common that there are mitochondria segments attached, which basically dues to the similarity between mitogenome and plastome or the horizontal transfer. Similar case could be found [here](https://github.com/Kinggerm/GetOrganelle/issues/5#issuecomment-470568496). 
If you take a look at the flowchart of GetOrganelle [here](https://github.com/Kinggerm/GetOrganelle#how-to), you would understand that GetOrganelle would automatically clean the assembly_graph.fastg, and pick the plastome graph and store it as a `gfa` file. In your three results, the final resulting -- `fasta` and `gfa` files should be identical, too. You can load `gfa` file with Bandage, you will see.
It's also fine to manually remove those contigs in Bandage and export the circular path. But this is not suggested because many users make mistakes in exporting the final result.

Let me know if you have further questions!
Good luck with your study!
J
