### ISSUE TITLE
Issue : Invalid characters

### ISSUE THREAD

**Issue by DylanDSouzaInd** [Kinggerm/GetOrganelle#262]
Hi, I am unable to run the following command both with assembly from reads and with assembly. 

Please guide how to resolve this. I have cleaned short reads as I obtained the sequence reads from BGI.

$ get_organelle_from_assembly.py -F fungus_mt -g spades_assembly_graph_with_scaffolds.gfa -o fungus_mt_out --overwrite

GetOrganelle v1.7.7.0

get_organelle_from_assembly.py isolates organelle genomes from assembly graph.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
PLATFORM: Linux optiplex-9020 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64
PYTHON LIBS: GetOrganelleLib 1.7.7.0; numpy 1.24.2; sympy 1.11.1; scipy 1.10.1
DEPENDENCIES: Blast 2.13.0; Bandage 0.8.1
GETORG_PATH=/home/dylan/.GetOrganelle
LABEL DB: fungus_mt 0.0.1
WORKING DIR: /media/dylan/Seagate Backup Plus Drive/projects/pen_gen/spades
/home/dylan/miniconda3/envs/assembly/bin/get_organelle_from_assembly.py -F fungus_mt -g spades_assembly_graph_with_scaffolds.gfa -o fungus_mt_out --overwrite

Traceback (most recent call last):
  File "/home/dylan/miniconda3/envs/assembly/bin/get_organelle_from_assembly.py", line 1072, in <module>
    main()
  File "/home/dylan/miniconda3/envs/assembly/bin/get_organelle_from_assembly.py", line 958, in main
    options, log_handler = get_options(description=title, version=get_versions())
  File "/home/dylan/miniconda3/envs/assembly/bin/get_organelle_from_assembly.py", line 402, in get_options
    assert is_valid_path(os.path.realpath(options.output_base)), \
AssertionError: Invalid characters (e.g. space, non-ascii) for SPAdes in path: /media/dylan/Seagate Backup Plus Drive/projects/pen_gen/spades/fungus_mt_out

**Comment by DylanDSouzaInd** [comment]
I figured that it wouldn't work through a mounted drive.

I succeeded by running it on the system with the conda environment.

**Comment by JianjunJin** [comment]
`BingChat` says, "It looks like you’re having an issue with the `get_organelle_from_assembly.py` script. The error message suggests that there are invalid characters in the path specified for the SPAdes output. Specifically, it seems that the space in the path `/media/dylan/Seagate Backup Plus Drive/projects/pen_gen/spades/fungus_mt_out` is causing the issue. You might want to try removing the space or replacing it with an underscore or another valid character."

The reason is not mounted drives, but the whitespace in the name of your drive. That is to say, I confirm that `BingChat` is correct.
