### ISSUE TITLE
more than one final fasta file

### ISSUE THREAD

**Issue by zijiangyang** [Kinggerm/GetOrganelle#30]
Hi:
I successfully assembled the plastid genome using GetOrganelle, however the output contains four fasta files, *1.1*fasta, *1.2*fasta, *1.3*fasta and *1.4*fasta. I checked the gfa file and it looks like this:

![plastidtest](https://user-images.githubusercontent.com/15051091/75229183-649b0200-57ec-11ea-90fd-d8aecfc9d241.png)

it contains 3 single copy regions and 3 repeat regions. Judging by the depth, one repeat region (the smallest one) appear three times and the other two appear two times. Since this plastid genome is different from the quadripartite structure, could this caused by assemble errors?

Many thanks!

**Comment by Kinggerm** [comment]
Hi,

This is not an assembly error. This assembly graph could be caused by A) a 237-bp repeat shared by both LSC and IR (in all cases I've seen), or B) an extra set of inverted repeats inside the canonical LSC (previously never observed, but there is a theoretical chance).
GetOrganelle by default will export all computationally-possible paths from this assembly graph. Of those 4 paths, 2 of them represent the A scenario and 2 of them represent the B scenario. I believe the A scenario is true as noted above, meaning 2 true ones are those have the "2,226 bp" contig as part of the IR. To find out which 2 ones fit the A scenario, you can turn on the "name" in Bandage and compare sequence name which denotes the path of that sequence.

To strictly confirm that it's really A rather than B scenario, or both, if you have paired-end reads with insert size larger than 250 bp, you could map those reads to all those paths to see if there exist pairs of reads spanning over 
1) 23846 bp -> 237 bp -> 59403 bp
2) 2226 bp -> 237 bp -> 20536 bp
3) 23846 bp -> 237 bp -> 20536 bp
4) 2226 bp -> 237 bp -> 59403 bp
If 1) & 2) exist, 3) & 4) not exist, A scenario is true, vise versa. If all of them exist, you really have something new. I hope you could still understand me well by using those lengths, if you turn on the contig name, I can describe those paths using names rather than using lengths.

**Comment by zijiangyang** [comment]
> Hi,
> This is not an assembly error. This assembly graph could be caused by A) a 237-bp repeat shared by both LSC and IR (in all cases I've seen), or B) an extra set of inverted repeats inside the canonical LSC (previously never observed, but there is a theoretical chance).
> GetOrganelle by default will export all computationally-possible paths from this assembly graph. Of those 4 paths, 2 of them represent the A scenario and 2 of them represent the B scenario. I believe the A scenario is true as noted above, meaning 2 true ones are those have the "2,226 bp" contig as part of the IR. To find out which 2 ones fit the A scenario, you can turn on the "name" in Bandage and compare sequence name which denotes the path of that sequence.
> To strictly confirm that it's really A rather than B scenario, or both, if you have paired-end reads with insert size larger than 250 bp, you could map those reads to all those paths to see if there exist pairs of reads spanning over
> 
> 23846 bp -> 237 bp -> 59403 bp
> 2226 bp -> 237 bp -> 20536 bp
> 23846 bp -> 237 bp -> 20536 bp
> 2226 bp -> 237 bp -> 59403 bp
> 
> If 1) & 2) exist, 3) & 4) not exist, A scenario is true, vise versa. If all of them exist, you really have something new. I hope you could still understand me well by using those lengths, if you turn on the contig name, I can describe those paths using names rather than using lengths.

Very clear! Probably it's scenario A, I'll try to map the paired end reads back to those fragments to confirm it.
Thanks again!

**Comment by Kinggerm** [comment]
> > Hi,
> > This is not an assembly error. This assembly graph could be caused by A) a 237-bp repeat shared by both LSC and IR (in all cases I've seen), or B) an extra set of inverted repeats inside the canonical LSC (previously never observed, but there is a theoretical chance).
> > GetOrganelle by default will export all computationally-possible paths from this assembly graph. Of those 4 paths, 2 of them represent the A scenario and 2 of them represent the B scenario. I believe the A scenario is true as noted above, meaning 2 true ones are those have the "2,226 bp" contig as part of the IR. To find out which 2 ones fit the A scenario, you can turn on the "name" in Bandage and compare sequence name which denotes the path of that sequence.
> > To strictly confirm that it's really A rather than B scenario, or both, if you have paired-end reads with insert size larger than 250 bp, you could map those reads to all those paths to see if there exist pairs of reads spanning over
> > 23846 bp -> 237 bp -> 59403 bp
> > 2226 bp -> 237 bp -> 20536 bp
> > 23846 bp -> 237 bp -> 20536 bp
> > 2226 bp -> 237 bp -> 59403 bp
> > If 1) & 2) exist, 3) & 4) not exist, A scenario is true, vise versa. If all of them exist, you really have something new. I hope you could still understand me well by using those lengths, if you turn on the contig name, I can describe those paths using names rather than using lengths.
> 
> Very clear! Probably it's scenario A, I'll try to map the paired end reads back to those fragments to confirm it.
> Thanks again!

I recommend mapping reads to complete sequences rather than fragments. Mapping to fragments causes unexpected barrier (e.g. fastg format contigs retain the overlap sequences) and sometimes may not reveal the true read-pair linkage.
