### ISSUE TITLE
 Disentangling failed: 'Unrecognized GFA version number: 1.2'

### ISSUE THREAD

**Issue by abdo3a** [Kinggerm/GetOrganelle#312]
Hello,
i got an error as ```Disentangling failed: 'Unrecognized GFA version number: 1.2``` with ```get_organelle_from_assembly.py ```.
i attached the full log file here. 
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/14313394/get_org.log.txt)

**Comment by JianjunJin** [comment]
Thanks for reaching out. The log is the answer. GetOrganelle cannot recognize GFA 1.2.
I haven't taken a close look at every format's uniqueness, but since GetOrganelle currently only uses nodes and edges, it should generally be fine to arbitrarily modify `1.2` into `1.0` in your input file.
If it still does not work, you may need to find tools to convert the format.

**Comment by abdo3a** [comment]
Thanks so much, it worked after modifying ```1.2``` into ```1.0``` in my input file. i will close this now
