### ISSUE TITLE
Crashes while running GetOrganelle

### ISSUE THREAD

**Issue by bioramg** [Kinggerm/GetOrganelle#32]
Hi,
I would like to extract plant mt genome from the whole raw data sequence. When I use Illumina pair-end reads (9 GB each), it stops suddenly. I tried several times. But the same issues. My server is having 188 GB RAM only. Is it possible to use the subsampling of Illumina RAW reads?

Also, I am having an ONT Nanopore raw data sequence (9 GB). Can I use together here to extract plant mt reads for the assembly using SPAdes? 
Please suggest to me. 
Thank you.

**Comment by Kinggerm** [comment]
Hi,

Please ALWAYS provide me with the get_org.log.txt file, otherwise I've no idea what your "crashes" issue was.

By default, GetOrganelle will automatically subsample if it's too much to have more than 500× base coverage. You can reduce the threshold (usually 200× is enough) by using "--reduce-reads-for-coverage 500". You can also directly subsample reads by "--max-reads *", where * is the number of reads.

GetOrganelle for ONT data is still under development. Currently, we find that current tools for organelle genome assembly with ONT data is problematic. I will keep you updated.

**Comment by bioramg** [comment]
Hi,
Thank you for your kind reply.

I tried yesterday also with the same commands and included --max-reads 75000000. But i faced the same issues and crashed in this step only. The server computer is not responding also.

I am herewith enclosing the log file for your reference, please find the attachment. 
Thank you.


[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/4302882/get_org.log.txt)

**Comment by Kinggerm** [comment]
Hi,

It seems that GetOrganelle hit the memory limit of your server.
According to the estimation, your data contains limited base coverage of mitogenome, so that GetOrganelle assigns a very small word size (-w 71). `The automatically-estimated parameter(s) do not ensure the best choice(s).` You could try to increase -w to reduce memory usage in this case, such as `-w 95`.

**Comment by bioramg** [comment]
Thank you for your valuable suggestions.
Sure. I will do and inform you.
I would like to know what should I give parameters for --reduce-reads-for-coverage inf?

Thank you.

**Comment by Kinggerm** [comment]
> Thank you for your valuable suggestions.
> Sure. I will do and inform you.
> I would like to know what should I give parameters for --reduce-reads-for-coverage inf?
> 
> Thank you.

`inf` is the parameter of `--reduce-reads-for-coverage`

**Comment by bioramg** [comment]
Thank you.

**Comment by Tiramisu023** [comment]
Hi,
I met the same problem as Issues https://github.com/Kinggerm/GetOrganelle/issues/32. I also would like to extract plant chloroplast genome and ITS sequences from the whole raw reads. Here is the server information: 1TB memery, 192 threads, usually 30% cpu usage.

I use the --reduce-reads-for-coverage inf --max-reads inf to include all raw reads :

nohup cat list.txt | xargs -i bash -c 'input={}; get_organelle_from_reads.py -1 {} -2 ${input/.R1./.R2.} -t 30 -o $(basename ${input%.R1*}_nr) -R 10 -k 35,85,115 -F embplant_nr --reduce-reads-for-coverage inf  --max-reads inf > /dev/null' &

head -2 list.txt
../01.raw_reads/CHLJ01_L3_UDI346.R1.fastq.gz
../01.raw_reads/CHQ05_L1_UDI300.R1.fastq.gz

The program terminates unexpectedly without any error message while assembling the second sample. The first log file runs successfully, while the second one fails. In total, I have about 100 samples to batch assemble.
[1.get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/13533646/1.get_org.log.txt)
[2.get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/13533647/2.get_org.log.txt)

Thank you.
