### ISSUE TITLE
--genes argument for animal/fungal mitochondrial assembly?

### ISSUE THREAD

**Issue by charlesfoster** [Kinggerm/GetOrganelle#35]
Hi,

Thanks for the great tool. I'm currently trying to assemble animal mitochondria. In the recipes section, the animal and fungal recipes contain "--genes animal_mt_genes.fasta". However, this "--genes" flag is missing from all other recipes. 

What exactly is the "--genes" flag doing differently to the "-s" seed flag? Is it necessary? If so, what is meant to be within the "animal_mt_genes.fasta" file? I note that no files in GetOrganelleLib correspond to "animal_mt_genes.fasta", and that I previously assembled an animal mitochondrial genome without including the "--genes" flag.

Thanks,
Charles

**Comment by Kinggerm** [comment]
Hi Charles,

Sorry for the delay. In short, If you assembled an animal mitogenome, you didn't need the "--genes" flag. You can just skip it.

The the "-s" is followed by the seed database, while "--genes" flag is followed by the label database. In fact, it's just the complete organelle genome used as seed, versus the genes used for labeling after assembly.
You won't find the "animal_mt.fasta" file in this repository, because, since 1.7.0, the default database has been isolated as another repo, [GetOrganelleDB](github.com/Kinggerm/GetOrganelleDB). But you can actually find them locally (GetOrganelle/GetOrganelleLib/LabelDatabase), after you install and initial GetOrganelle. If you don't assign a user one (no "--genes"), GetOrganelle will use the default one, which luckily works for your taxa.
However, while the fungus and animal mitogenomes are so divergent, our default database is currently limited for maybe 70% fungus and animal mitogenomes. Plant plastomes and mitogenomes won't have such a problem because of their slow rate. This is part of the reasons why we isolate the default database as an independent repo - we are going to update it and expand it in versions.

Thanks for the feedback. I'm going to update the recipe so that people could understand better. Please let me know if you have further questions.

Jianjun
