### ISSUE TITLE
How to assign the number of reads for assembly? 

### ISSUE THREAD

**Issue by daicy527** [Kinggerm/GetOrganelle#352]
**First check**
- [ ] I used the GitHub search to find a similar issue or discussion and didn't find it.
- [ ] I searched [GetOrganelle.wiki](https://github.com/Kinggerm/GetOrganelle/wiki) context, especially the [FAQ](https://github.com/Kinggerm/GetOrganelle/wiki/FAQ) and browsed the [examples](https://github.com/Kinggerm/GetOrganelle/wiki/Examples) to confirm it is unexpected to happen.
- [ ] I have updated GetOrganelle to the latest released version [![GitHub release](https://img.shields.io/github/release/Kinggerm/GetOrganelle.svg)](https://GitHub.com/Kinggerm/GetOrganelle/releases/)

Please ask questions in the [Question in GitHub Discussions](https://github.com/Kinggerm/GetOrganelle/discussions/categories/q-a) unless it is a feature request or bug report.

Dear all,
Currently, it seems the program can estimate the number of reads for assembly. Alternatively, it can set to use all the available reads.  Does anyone know how to use an assigned number of reads for assembly? 
Many thanks.

**Comment by JianjunJin** [comment]
See https://github.com/Kinggerm/GetOrganelle/wiki/Usage#main-scripts, by using `--max-reads INT` and `--reduce-reads-for-coverage inf` together, where INT is your assigned number of reads per file, you can assign the number of reads for the analysis. However, the analysis does not necessarily mean assembly due to the filtering process.

Highly Related: 
- https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#how-many-reads-shall-i-input
- https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#what-is-the-coverage-of-the-assembly
