### ISSUE TITLE
How to use our own library instead of embplant_pt

### ISSUE THREAD

**Issue by JoshPhd** [Kinggerm/GetOrganelle#59]

**Comment by Kinggerm** [comment]
You could check `get_organelle_from_reads.py --help` for detailed illustration of all options.
--
The question is not specific enough. I guess you want to assemble plastome from embryophytes but with your own seed/label database (let me know if I misunderstand). So you should always input `-F embplant_pt` to let GetOrganelle know the type of organelle genome.
`-s customized_plastome.fasta` is for inputing your seed database in place of the default `GetOrganelleLib/SeedDatabase/embplant_pt.fasta`. This is recommend for benchmark test or when your data is not very good.
`--genes customized_gene_set.fasta` is for inputing your label database in place of the default `GetOrganelleLib/LabelDatabase/embplant_pt.fasta`. But this label database replacement is basically unnecessary because gene sequences are generally conserved and the default one is sufficient.

**Comment by JoshPhd** [comment]
Thanks for your reply.
We tried to use our own seed database and your suggestions was very useful.
It was a really good software for plastome assembly.
