### ISSUE TITLE
Problem running

### ISSUE THREAD

**Issue by AllisonStander** [Kinggerm/GetOrganelle#7]
Good day,

I am having trouble running GetOrganelle on our cluster.

My command for running GetOrganelle:

`singularity exec /tools/containers/getorganelle/getorganelle-test-1.simg get_organelle_reads.py -1 /usr/people/astander/00_GenomeRooibos/00_Data/00_RawData/L5_R1.fastq -2 /usr/people/astander/00_GenomeRooibos/00_Data/00_RawData/L5_R2.fastq -o /usr/people/astander/00_GenomeRooibos/06_Chloroplast/00_GetOrganelle/chloroplast_output_L5 -R 15 -k 45,65,85,105 -F plant_cp`

The log file:

```
GetOrganelle v1.5.1c

gets organelle reads and genomes from genome skimming data by extending.
Find updates in https://github.com/Kinggerm/GetOrganelle and see README.md for more information.

Python 3.7.1 (default, Dec 14 2018, 19:28:38)
[GCC 7.3.0]
/GetOrganelle/get_organelle_reads.py -1 /usr/people/astander/00_GenomeRooibos/00_Data/00_RawData/L5_R1.fastq -2 /usr/people/astander/00_GenomeRooibos/00_Data/00_RawData/L5_R2.fastq -o /usr/people/astander/00_GenomeRooibos/06_Chloroplast/00_GetOrganelle/chloroplast_output_L5 -R 15 -k 45,65,85,105 -F plant_cp

2019-03-25 15:02:59,898 - INFO: Pre-reading fastq ...
2019-03-25 15:02:59,899 - INFO: Counting read qualities ...
2019-03-25 15:03:23,316 - INFO: Number of reads exceeded 15000000 in L5_R1.fastq, only top 15000000 reads are used in downstream analysis.
2019-03-25 15:03:46,312 - INFO: Number of reads exceeded 15000000 in L5_R2.fastq, only top 15000000 reads are used in downstream analysis.
2019-03-25 15:04:04,830 - INFO: Identified quality encoding format = Sanger
2019-03-25 15:04:05,080 - INFO: Trimming bases with qualities (0.00%): 33..33  !
2019-03-25 15:04:15,128 - INFO: Mean error rate = 0.0019
2019-03-25 15:04:15,267 - INFO: Counting read lengths ...
2019-03-25 15:05:06,647 - INFO: Mean = 119.9 bp, maximum = 125 bp.
2019-03-25 15:05:06,647 - INFO: Reads used = 30000000
2019-03-25 15:05:06,647 - INFO: Pre-reading fastq finished.

2019-03-25 15:05:06,647 - INFO: Making seed reads ...
2019-03-25 15:05:06,653 - INFO: Making seed - bowtie2 index ...
2019-03-25 15:05:06,729 - ERROR:
Settings:
 Output files: "/GetOrganelle/Library/SeqReference/plant_cp.fasta.index.*.bt2l"
 Line rate: 7 (line is 128 bytes)
 Lines per side: 1 (side is 128 bytes)
 Offset rate: 4 (one in 16)
 FTable chars: 10
 Strings: unpacked
 Max bucket size: default
 Max bucket size, sqrt multiplier: default
 Max bucket size, len divisor: 4
 Difference-cover sample period: 1024
 Endianness: little
 Actual local endianness: little
 Sanity checking: disabled
 Assertions: disabled
 Random seed: 0
 Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
 /GetOrganelle/Library/SeqReference/plant_cp.fasta
Building a LARGE index
Reading reference sizes
Could not open index file for writing: "/GetOrganelle/Library/SeqReference/plant_cp.fasta.index.3.bt2l"
Please make sure the directory exists and that permissions allow writing by
Bowtie.
 Time reading reference sizes: 00:00:00
Total time for call to driver() for forward index: 00:00:00
Error: Encountered internal Bowtie 2 exception (#1)
Command: /opt/miniconda/bin/bowtie2-build-l --wrapper basic-0 /GetOrganelle/Library/SeqReference/plant_cp.fasta /GetOrganelle/Library/SeqReference/plant_cp.fasta.index
Deleting "/GetOrganelle/Library/SeqReference/plant_cp.fasta.index.3.bt2l" file written during aborted indexing attempt.
Deleting "/GetOrganelle/Library/SeqReference/plant_cp.fasta.index.4.bt2l" file written during aborted indexing attempt.

2019-03-25 15:05:06,730 - ERROR:
Traceback (most recent call last):
 File "/GetOrganelle/get_organelle_reads.py", line 2557, in main
   log=log)
 File "/GetOrganelle/get_organelle_reads.py", line 1846, in mapping_with_bowtie2
   exit()
 File "/opt/miniconda/lib/python3.7/_sitebuiltins.py", line 26, in __call__
   raise SystemExit(code)
SystemExit: None

Total cost 127.85 s
Please email phylojianjun@163.com or jinjianjun@mail.kib.ac.cn if you find bugs!
Please provide me with the get_org.log.txt file!
```

Any idea as to what is happening, or how I can fix it?

Kind regards,
Allison

**Comment by Kinggerm** [comment]
Hi Allison,

You installed GetOrganelle in the root directory as I saw from log, it might be the permission issue. You should make the directory writable for Bowtie2 to output the index. You might also need to add `sudo` before `chmod`:
> sudo chmod +w /GetOrganelle/Library/SeqReference

Please let me know the updates. Good luck!

Jianjun

**Comment by Banshee1221** [comment]
Hi Jianjun

The way that you provide the library is not conducive to running this tool in a shared (cluster) environment nor through containers since. 

We run bioinformatics tools in Singularity containers and I've solved Allison's issue by cloning the repo in her $HOME, followed by specifying the container of your tool (which I packaged) with the -s flag to her $HOME/GetOrganelle/Library.

I would suggest perhaps looking at ways of splitting the library out and allowing it to be pulled in at runtime per user to the user's directory? This would alleviate the issues with multiple users trying to run it at the same time or run it via containers.

Eugene

**Comment by Kinggerm** [comment]
Hi Eugene,

Actually once bowtie2 index was made for the first time, the index could be shared and would not be overwritten any more in this version of GetOrganelle. I mean there would not be a problem for multiple users to access it simultaneously. However it is indeed not a good way to configure bioinformatics tools - writing stuff back to the bin directory even only for the first time. You are absolutely right at that point.
I had thought of making the index into the sample directory because making the bowtie2 index is actually very fast and space-costless.
Thank you very much for the suggestion and thanks for helping Allison!

Jianjun

**Comment by Kinggerm** [comment]
Hi Eugene and Allison,

I just made the change which is making the index into the user assigned output directory. Let me know if you have any other suggestions!

Jianjun

**Comment by Banshee1221** [comment]
I will hopefully get around to testing this soon, but I think you can close this issue now. Thanks so much for the quick feedback!
