### ISSUE TITLE
Windows Subsystem for Linux error - Unexpected stopped at "Assembling using SPAdes" steps

### ISSUE THREAD

**Issue by ChenJuiYANG** [Kinggerm/GetOrganelle#71]
[get_org.log.txt](https://github.com/Kinggerm/GetOrganelle/files/6283243/get_org.log.txt)

Hi there, 

I failed with running the test file provided on Github. It always stopped at "Assembling using SPAdes" steps and I can't do anything such as Ctrl+c to aboard the program. (Waiting for more than an hour)
It also failed when running my real data and stopped at the same steps. 

Is this because I run the program in Ubuntu linux system with Windows Subsystem for Linux (WSL) on Win10? 
And after all, I have to use an independent Linux system?

Could someone help me to solve this? Thanks a lot. 

Processor: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz   2.59 GHz
RAM: 8.00 GB

The log file is in attachment.

**Comment by Kinggerm** [comment]
Windows Subsystem Linux is currently not supported due to SPAdes's not officially maintained for WSL(https://github.com/ablab/spades/issues/682#issuecomment-797710452). However, a few users reported that they were able to run it on WSL when install spades using `apt install`, while some others failed to make it using the same way.

You may try uninstalling the conda SPAdes and install SPAdes using `apt install` to see if it works for you. Otherwise, please run GetOrganelle in a pure linux system instead (could be inside a virtual machine).

BTW, this long waiting behavior has been corrected in 1.7.3.5b and later versions (only available through github).

**Comment by ChenJuiYANG** [comment]
Do you know how to uninstall and re-install conda SPAdes solely? When I uninstalled SPAdes, many packages (including GetOrganelle) seems had been uninstalled together. I think that's because of the dependencies.

**Comment by Kinggerm** [comment]
You may switch to install GetOrganelle [using the setup.py](https://github.com/Kinggerm/GetOrganelle/wiki/Installation#option-2-using-the-setuppy).
